# Generated by Django 5.2.11 on 2026-02-24 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0007_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
